# Generated by Django 5.1.1 on 2024-11-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hoodie', 'Hoodie'), ('tshirt', 'T-Shirt'), ('accessory', 'Accessory'), ('sale', 'Sale')], max_length=50, null=True),
        ),
    ]
